### ISSUE TITLE
example usage doesn't work

### ISSUE THREAD

**Issue by mmkal** [commodityvectors/scalatest-snapshot-matchers#5]
Hi, I'd love to try out this library, but the example you have on the readme doesn't seem to work. First, there's a `com.` missing in the first import. But even with that corrected, I get this error on the line `myStateProcessor.state should matchSnapshot()`:

![image](https://user-images.githubusercontent.com/15040698/39157915-2c68caa8-472b-11e8-9fab-a3ab12a0cea9.png)

This is using scalatest 3.0.0 and snapshot matcher version 2.0.1 - any advice?

**Comment by mmkal** [comment]
Ah, found that it does work if I change it to `myStateProcessor.state should matchSnapshot[StateProcessorValue]()`. It seems like type inference should be able to catch this if the generic for the value being `should`ed was passed correctly? Otherwise worth updating the readme.

**Comment by grillorafael** [comment]
Hi @mmkal thank you for reaching us.

I'll update the readme and will look into a way to avoid specifying the type parameter.

Can  you check if you test compiles and runs without specifying the type parameter? I checked one of the tests here and I have intellij complaining but it compiles and run just fine.

I'll look into what can be causing that.

**Comment by grillorafael** [comment]
Hi @mmkal can you check if this branch makes it better? https://github.com/commodityvectors/scalatest-snapshot-matchers/pull/6

**Comment by grillorafael** [comment]
Try to use `2.0.2`. Problem should be fixed there.

**Comment by mmkal** [comment]
It works - thanks!
